def github(name, version, options = nil)
  options ||= {}
  options[:repo] ||= "boxen/puppet-#{name}"
  mod name, version, :github_tarball => options[:repo]
end

github "boxen",      "2.0.0"
github "homebrew",   "1.2.0"
github "repository", "2.0.0"
github "stdlib",     "3.0.0", :repo => "puppetlabs/puppetlabs-stdlib"
